plugins:
  - import
settings:
  import/parser: babel-eslint
  import/resolve:
    moduleDirectory:
      - node_modules
      - src
rules:
  import/default: 0
  import/no-duplicates: 0
  import/named: 0
  import/namespace: 0
  import/no-unresolved: 0
  import/no-named-as-default: 2
  jsx-a11y/anchor-is-valid: 0
  no-underscore-dangle: 0
  new-cap: 0
  import/extensions: 0